- name: apache2 copy 000-default.conf
  copy:
    src: ./config/apache2/sites-available/000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    # group: root

- name: apache2 copy apache2.conf
  copy:
    src: ./config/apache2/apache2.conf
    dest: /etc/apache2/apache2.conf
    owner: root
    # group: root

- name: Enable the Apache2 module rewrite
  community.general.apache2_module:
    state: present
    name: rewrite

- name: Enable the Apache2 module cgi
  community.general.apache2_module:
    state: present
    name: cgi
