### Role to install specific system related package repositories ###
### Created on: Dec 2019
### Author:     Thomas Bauer - iDiv
---
# SETUP OpenCL (VAT-MAPPING system requirement)
# Intel Compute Runtime to use OpenCL
# https://github.com/intel/compute-runtime/blob/master/documentation/Neo_in_distributions.md
# https://software.intel.com/en-us/articles/opencl-drivers#latest_linux_driver
- name: Add ppa PHP Repo
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes

- name: Add ppa apache2 Repo
  apt_repository:
    repo: ppa:ondrej/apache2
    state: present
    update_cache: yes

- name: Add ppa Intel OpenCL Repository for Ubuntu 18.04
  apt_repository:
    repo: ppa:intel-opencl/intel-opencl
    state: present
    update_cache: yes

# SETUP UbuntuGIS (VAT-MAPPING system requirement)
# - name: Add ppa UbuntuGIS Repository for Ubuntu 18.04
#   apt_repository:
#     repo: ppa:ubuntugis/ppa
#     state: present
#     update_cache: yes

- name: Add ppa UbuntuGIS unstable Repository for Ubuntu 18.04
  apt_repository:
    repo: ppa:ubuntugis/ubuntugis-unstable
    state: present
    update_cache: yes

# SETUP Cmake newest bionic release (VAT-MAPPING system requirement)
# https://apt.kitware.com/
# This is Kitware, Inc.'s third-party APT repository, which we use for hosting our own Ubuntu packages, such as CMake.
- name: Add the Kitware package signing key
  apt:
    name: "kitware-archive-keyring"
    state: latest

- name: Add Kitware APT Repository to get newest Version of Cmake
  apt_repository:
    repo: "deb https://apt.kitware.com/ubuntu/ bionic main"
    state: present
    update_cache: yes

# SETUP Nodejs for using Angular framework (VAT-Visualizer system requirement)
- name: Add the NodeSource package signing key
  shell:
    cmd: curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -

- name: Add Node.js LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

# SETUP Docker for development environments (development server only)
# - name: Add the Docker package signing key
#   shell:
#     cmd: curl -sSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

# - name: Add Docker Ubuntu bionic stable repos
#   apt_repository:
#     repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
#     state: present
#     update_cache: yes

# - name: Download the current Docker Compose release bin
#   shell:
#     cmd: curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

# - name: Apply executable permissions to the Docker Compose bin
#   shell:
#     cmd: chmod +x /usr/local/bin/docker-compose

# SETUP MYSQL FOR CATALOG
- name: Add the mysql 8.15 repository for ubuntu
  shell:
    cmd: wget https://dev.mysql.com/get/mysql-apt-config_0.8.15-1_all.deb

- name: Update apt
  apt:
    update_cache: yes
