PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE users ( userid INTEGER PRIMARY KEY, username STRING NOT NULL, realname STRING NOT NULL, email STRING NOT NULL, pwhash STRING NOT NULL, externalid STRING);
INSERT INTO users VALUES(1,'guest','guest','guest','7qg6CMZI:d6015121dc13c486f7fbbb5f99f751df76645ef3',NULL);
CREATE TABLE user_permissions ( userid INTEGER NOT NULL, permission STRING NOT NULL, PRIMARY KEY(userid, permission));
INSERT INTO user_permissions VALUES(1,'data.ogr_source.ne_10m_admin_0_countries_as layer_by_rasterid');
INSERT INTO user_permissions VALUES(1,'data.gdal_source.ne_10m_admin_0_countries_as_raster');
CREATE TABLE groups ( groupid INTEGER PRIMARY KEY, groupname STRING NOT NULL);
INSERT INTO "groups" VALUES(1,'users');
CREATE TABLE group_permissions ( groupid INTEGER NOT NULL, permission STRING NOT NULL, PRIMARY KEY(groupid, permission));
INSERT INTO group_permissions VALUES(1,'data.ogr_source.ne_10m_admin_0_countries_as layer_by_rasterid');
INSERT INTO group_permissions VALUES(1,'data.gdal_source.ne_10m_admin_0_countries_as_raster');
CREATE TABLE user_to_group ( userid INTEGER, groupid INTEGER, PRIMARY KEY(userid, groupid));
INSERT INTO user_to_group VALUES(1,1);
CREATE TABLE sessions ( sessiontoken STRING PRIMARY KEY, userid INTEGER NOT NULL, expires INTEGER NOT NULL);
INSERT INTO sessions VALUES('dWSStGRtsoxtwZspKKtdCb2wjKY66Bv9',1,1584742184);
INSERT INTO sessions VALUES('IDRsUzeRuJd0ENqRkc0iRkLeJc1Hc9C8',1,1584742226);
INSERT INTO sessions VALUES('GHs06bIbtISFx253NA5rJNH3J8yYbRcU',1,1585013770);
INSERT INTO sessions VALUES('BCBLc4UZtp3yx5jAolcZtHhyeo9MFhUy',1,1585066270);
INSERT INTO sessions VALUES('PQlqHbXoAx4ZiloEUIwnAz3MkivoeIiW',1,1585324370);
INSERT INTO sessions VALUES('JMs0w5m3gNHIILlrv6s4qMHT0NioNACW',1,1590599711);
CREATE TABLE artifacts ( artifactid INTEGER PRIMARY KEY, userid INTEGER NOT NULL, type STRING NOT NULL, name STRING NOT NULL, UNIQUE (userid, type, name) );
CREATE TABLE artifact_versions ( artifactid INTEGER, timestamp DATETIME NOT NULL, value STRING NOT NULL, PRIMARY KEY(artifactid, timestamp), FOREIGN KEY(artifactid) REFERENCES artifacts(artifactid) ON DELETE CASCADE);
CREATE UNIQUE INDEX unique_username ON users(username);
CREATE UNIQUE INDEX unique_externalid ON users(externalid);
CREATE UNIQUE INDEX unique_groupname ON groups(groupname);
COMMIT;
